### ISSUE TITLE
iCloud remote used in mock test

### ISSUE THREAD

**Issue by mariushegele** [Ovakefali13/buerro#65]
https://github.com/Ovakefali13/buerro/blob/ed9fb0e3142c7808faf5d8c54174ce2532856acb/usecase/lunchbreak/lunch.py#L117

https://github.com/Ovakefali13/buerro/blob/ed9fb0e3142c7808faf5d8c54174ce2532856acb/usecase/lunchbreak/lunch.py#L92

@timozuther 

The CalService is instantiated with the iCloud Remote non-regarding of whether we are in a mock or non-mocking test. 

Also you might think about moving the setting of Mock remotes and services out of the class into the test. Even though it might require some setters, I feel like it shouldn't the classes responsibility to handle mocking.

**Comment by mariushegele** [comment]
The main issue is that iCloud remotes in mock tests heavily slow down the mock tests.

**Comment by timozuther** [comment]
I will change that. But would it be possible, that you could implement Calender as a singelton? By doing so, I would just have to set the remote one and I would not have to save the calender object as a class variable which would help with a potential multi user setup.
